apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno 
  namespace: flux-system
spec:
  releaseName: kyverno 
  targetNamespace: kyverno 
  interval: 10m
  chart:
    spec:
      chart: kyverno 
      version: v1.13.0 
      sourceRef:
        kind: HelmRepository
        name: kyverno 
        namespace: flux-system
  values:
    admissionController:
      replicas: 3
    backgroundController:
      replicas: 3
    cleanupController:
      replicas: 3
    reportsController:
      replicas: 3