apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-tenant-id 
  namespace: ${platformNamespace} 
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secret-store 
    kind: SecretStore
  target:
    name: platform-tenant-id 
    creationPolicy: Owner
  data:
  - secretKey: platform-tenant-id 
    remoteRef:
      key: secret/homelab--config--platformTenantId