apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aso 
  namespace: flux-system
spec:
  interval: 1m
  url: https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts 