apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane-system
  namespace: flux-system
spec:
  releaseName: crossplane
  interval: 5m
  chart:
    spec:
      chart: crossplane
      version: '1.18.0'
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system 
      interval: 1m