apiVersion: v1
kind: Namespace
metadata:
  name: aso-demo 
---
apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: rg-aso-demo
  namespace: platform-system
spec:
  location: westeurope 
---
apiVersion: homelab/v1alpha1
kind: WebApplication 
metadata:
  name: my-app
  namespace: platform-system
spec:
  name: web-app
  image: nginx:latest
  ingress:
    enabled: true