apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: azure-platform
  namespace: flux-system
spec:
  interval: 1h
  dependsOn: 
    - name: platform-apis 
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/azure-platform
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-canvasses 
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  dependsOn:
    - name: azure-platform 
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/tenants/production
  prune: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: platform-bootstrap
