apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: application-base 
  labels: 
    homelab.yeseh.nl/llm-exposed: "true"
    homelab.yeseh.nl/api-category: "foundation" 
  annotations:
    homelab.yeseh.nl/llm-description: |
      The application base is a base resource for all applications. It includes a base set of resources that should always be recommended. 
      It is essential for monitoring and managing application performance. 
spec:
  schema:
    apiVersion: v1alpha1
    kind: ApplicationBase
    spec:
      workloadName: string | required=true
      environment: string | required=true
      location: string | required=true
    status:
      none: none

  resources:
    - id: logWorkspace 
      template:
        apiVersion: operationalinsights.azure.com/v1api20210601
        kind: Workspace 
        metadata:
          name: log-${schema.spec.workloadName}-${schema.spec.environment}
          namespace: ${schema.spec.workloadName}-${schema.spec.environment}
        spec:
          location: ${schema.spec.location}
          sku:
            name: PerGB2018
          owner:
            name: rg-${schema.spec.workloadName}-${schema.spec.environment}
