# Canvas is deployed with the platform identity and resides in the homelab-system namespace
# It should setup authentication for the canvas identity to take over for workload resources 
# A canvas corresponds to a single application environment, azure subscription, and namespace in the platform cluster
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: canvas 
spec:
  schema:
    apiVersion: v1alpha1
    kind: Canvas 
    spec:
      workloadName: string | required=true
      environment: string | required=true
      location: string | required=true
      tenantId: string | required=true
      subscriptionId: string | required=true
    status: 
      resourceGroupName: ${resourceGroup.status.name}
      azureLocation: ${resourceGroup.status.location}
      test: bla
      # deploymentIdentityId: ${identity.status.id}
      # deploymentIdentityClientId: ${identity.status.clientId}
      # keyvaultId: ${keyvault.status.id}
      # tenantId: ${schema.spec.tenantId}
      # subscriptionId: ${schema.spec.subscriptionId}

  resources:
    # Create the canvas namespace
    - id: canvasNamespace 
      template:
        apiVersion: v1 
        kind: Namespace
        metadata:
          name: canvas-${schema.spec.workloadName}-${schema.spec.environment}

    # Create a config map in the canvas namespace that holds the canvas specific information
    - id: configmap
      template:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: canvas-config
          namespace: ${canvasNamespace.metadata.name}
        data: 
          namespace: ${canvasNamespace.metadata.name}
          serviceAccountName: canvas-identity
          subscriptionId: ${schema.spec.subscriptionId}
          tenantId: ${schema.spec.tenantId}

    - id: resourceGroup
      template:
        apiVersion: resources.azure.com/v1api20200601
        kind: ResourceGroup
        metadata:
          name: rg-${schema.spec.workloadName}-${schema.spec.environment}
          namespace: homelab-system 
        spec:
          location: ${schema.spec.location}

    - id: identity 
      template:
        apiVersion: managedidentity.azure.com/v1api20230131
        kind: UserAssignedIdentity
        metadata:
          name: id-${schema.spec.workloadName}-${schema.spec.environment}
          namespace: homelab-system 
        spec:
          location: ${resourceGroup.status.location}
          owner:
            name: ${resourceGroup.status.name}
          operatorSpec:
            configMaps:
              principalId:
                key: principalId
                name: canvas-config
              clientId:
                key: clientId 
                name: canvas-config

    # - id: federatedCredential
    #   apiVersion: managedidentity.azure.com/v1api20220131preview
    #   kind: FederatedIdentityCredential
    #   metadata:
    #     name: fic-${schema.spec.workloadName}-${schema.spec.environment}-canvas
    #     namespace: ${canvasNamespace.metadata.name}
    #   spec:
    #     subject: system:serviceaccount:${canvasNamespace.metadata.name}:canvas-identity
    #     owner:
    #       name: ${identity.status.id} 
    #     audiences:
    #       - api://AzureADTokenExchange
    #     issuerFromConfig:
    #       name: platform-bootstrap
    #       key: platformClusterOidcIssuer

    # # The service account linked to the deployment identity
    # # Used to enforce tenant separation in fluxcd deployments 
    # - id: serviceAccount 
    #   template:
    #     apiVersion: v1
    #     metadata: 
    #       name: ${configmap.data.serviceAccountName} 
    #       namespace: ${canvasNamespace.metadata.name}
    #       annotations:
    #         azure.workload.identity/client-id: ${identity.status.clientId} 
    #         azure.workload.identity/tenant-id: ${schema.spec.tenantId} 




# Keyvault
# Secret store
# Managed identity
# Vnet
# Subnet