apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: platform-secret-store 
  namespace: ${platformNamespace}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: ${platformKeyvaultUri} 
      serviceAccountRef:
        name: ${platformExternalSecretsServiceAccountName} 