apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kro 
  namespace: kro 
spec:
  interval: 5m
  chart:
    spec:
      chartRef:
        kind: OCIRepository 
        name: kro 
        namespace: flux-system 