apiVersion: kro.run/v1alpha1
kind: Canvas 
metadata:
  name: canvas-platform-api
  namespace: homelab-system 
spec:
  workloadName: hlplatformapi
  environment: prd 
  location: westeurope
  tenantId: ${platformTenantId}
  subscriptionId: ${platformSubscriptionId}
  oidcIssuer: ${platformClusterOidcIssuer}