name: build-simple-api
on:
  pull_request:
  push:
    paths:
      - apps/simple-api/**
      - .github/workflows/build-simple-api.yaml
    branches:
      - main 
    
concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/simple-api
    timeout-minutes: 30 
    steps:
      - uses: actions/checkout@v4
      # install zig
      - uses: mlugg/setup-zig@v1

      # Build test and build the application
      - run: zig build test
      - run: zig build --release=fast

      # Create an image in the homelab registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{github.repository}}/simple-api

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: apps/simple-api
          file: apps/simple-api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}